2025-02-07 15:53:49,713 DEBUG    root            Loaded Command Group: ['gcloud', 'auth']
2025-02-07 15:53:49,715 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'application_default']
2025-02-07 15:53:49,724 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'application-default', 'login']
2025-02-07 15:53:49,725 DEBUG    root            Running [gcloud.auth.application-default.login] with arguments: []
2025-02-07 15:53:49,763 DEBUG    requests_oauthlib.oauth2_session Generated new state Z4DpuVtfQ6HqIMoBMdykWuH815zuUc.
2025-02-07 15:53:49,896 INFO     ___FILE_ONLY___ Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=Z4DpuVtfQ6HqIMoBMdykWuH815zuUc&access_type=offline&code_challenge=cuZ5bueP6n1_YHl2QMjS9NdIj3yrN77UEz5NbDWg0Ho&code_challenge_method=S256


2025-02-07 15:53:54,020 INFO     google_auth_oauthlib.flow "GET /?error=access_denied&state=Z4DpuVtfQ6HqIMoBMdykWuH815zuUc HTTP/1.1" 200 1027
2025-02-07 15:53:54,021 DEBUG    root            (missing_code) Missing code parameter in response.
Traceback (most recent call last):
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 815, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/surface/auth/application_default/login.py", line 210, in Run
    creds = auth_util.DoInstalledAppBrowserFlowGoogleAuth(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/api_lib/auth/util.py", line 357, in DoInstalledAppBrowserFlowGoogleAuth
    user_creds = BrowserFlowWithNoBrowserFallbackRunner(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/api_lib/auth/util.py", line 145, in Run
    return self._flow.Run(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/core/credentials/flow.py", line 243, in Run
    return self._Run(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/core/credentials/flow.py", line 342, in _Run
    self.fetch_token(
  File "/Users/tamjid/google-cloud-sdk/lib/third_party/google_auth_oauthlib/flow.py", line 300, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/third_party/requests_oauthlib/oauth2_session.py", line 233, in fetch_token
    self._client.parse_request_uri_response(
  File "/Users/tamjid/google-cloud-sdk/lib/third_party/oauthlib/oauth2/rfc6749/clients/web_application.py", line 240, in parse_request_uri_response
    response = parse_authorization_code_response(uri, state=state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/third_party/oauthlib/oauth2/rfc6749/parameters.py", line 278, in parse_authorization_code_response
    raise MissingCodeError('Missing code parameter in response.')
oauthlib.oauth2.rfc6749.errors.MissingCodeError: (missing_code) Missing code parameter in response.
2025-02-07 15:53:54,037 ERROR    ___FILE_ONLY___ BEGIN CRASH STACKTRACE
Traceback (most recent call last):
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/command_lib/crash_handling.py", line 199, in Wrapper
    target_function(*args, **kwargs)
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/gcloud_main.py", line 194, in main
    gcloud_cli.Execute()
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 1024, in Execute
    self._HandleAllErrors(exc, command_path_string, specified_arg_names)
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 1061, in _HandleAllErrors
    exceptions.HandleError(exc, command_path_string, self.__known_error_handler)
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/calliope/exceptions.py", line 557, in HandleError
    core_exceptions.reraise(exc)
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/core/exceptions.py", line 149, in reraise
    six.reraise(type(exc_value), exc_value, tb)
  File "/Users/tamjid/google-cloud-sdk/lib/third_party/six/__init__.py", line 719, in reraise
    raise value
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 815, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/surface/auth/application_default/login.py", line 210, in Run
    creds = auth_util.DoInstalledAppBrowserFlowGoogleAuth(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/api_lib/auth/util.py", line 357, in DoInstalledAppBrowserFlowGoogleAuth
    user_creds = BrowserFlowWithNoBrowserFallbackRunner(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/api_lib/auth/util.py", line 145, in Run
    return self._flow.Run(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/core/credentials/flow.py", line 243, in Run
    return self._Run(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/core/credentials/flow.py", line 342, in _Run
    self.fetch_token(
  File "/Users/tamjid/google-cloud-sdk/lib/third_party/google_auth_oauthlib/flow.py", line 300, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/third_party/requests_oauthlib/oauth2_session.py", line 233, in fetch_token
    self._client.parse_request_uri_response(
  File "/Users/tamjid/google-cloud-sdk/lib/third_party/oauthlib/oauth2/rfc6749/clients/web_application.py", line 240, in parse_request_uri_response
    response = parse_authorization_code_response(uri, state=state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/third_party/oauthlib/oauth2/rfc6749/parameters.py", line 278, in parse_authorization_code_response
    raise MissingCodeError('Missing code parameter in response.')
oauthlib.oauth2.rfc6749.errors.MissingCodeError: (missing_code) Missing code parameter in response.
2025-02-07 15:53:54,041 ERROR    root            gcloud crashed (MissingCodeError): (missing_code) Missing code parameter in response.
2025-02-07 15:53:54,041 INFO     ___FILE_ONLY___ 
If you would like to report this issue, please run the following command:

2025-02-07 15:53:54,041 INFO     ___FILE_ONLY___   gcloud feedback

2025-02-07 15:53:54,041 INFO     ___FILE_ONLY___ 
To check gcloud for common problems, please run the following command:

2025-02-07 15:53:54,041 INFO     ___FILE_ONLY___   gcloud info --run-diagnostics

